? FE/S3 - Implement file uploading mechanics [Q]
binaryx-protocol/binaryx_app pull request #104
Opened 2022-12-21 17:50 UTC by Space-zee

https://app.clickup.com/t/33z1mch

2022-12-21 21:43 UTC, ruslanpalagin requested changes

2022-12-21 21:43 UTC, ruslanpalagin commented on api/src/features/assets/asset.service.ts
> +    console.log('imagesUrlArray', imagesUrlArray);
rm log please

2022-12-21 21:43 UTC, ruslanpalagin commented on frontend/app/features/assets/controllers/NewAssetController.tsx
> +    axios.post('http://localhost:3001/assets/create', {
use core/http-client

2022-12-21 21:43 UTC, ruslanpalagin commented on frontend/package.json
> +    "axios": "^1.2.1",
no need for axios. use core/http-client

2022-12-22 09:25 UTC, Space-zee commented on api/src/features/assets/asset.service.ts
> +    console.log('imagesUrlArray', imagesUrlArray);
+

2022-12-22 11:53 UTC, ruslanpalagin approved these changes

2022-12-22 11:53 UTC, merged