feat:SC-account-details
binaryx-protocol/binaryx_app pull request #118
Opened 2022-12-29 18:52 UTC by Space-zee

2022-12-29 19:05 UTC, ruslanpalagin requested changes

2022-12-29 19:05 UTC, ruslanpalagin commented on api/src/features/assets/assets.controller.ts
> +  @Post('array')
sorry but this is a mess if we are trying to achieve REST API
we need to discuss it

2022-12-29 19:05 UTC, ruslanpalagin commented on frontend/app/abis/UiProvider.json
> +[
1 why do we need so huge abi? can we put those 2 methods here?

2022-12-29 19:05 UTC, ruslanpalagin commented on frontend/app/features/account/models/accountModel.ts
> +  console.log('response', response)
please remove logs unless they are verbose AND needed

2022-12-30 11:15 UTC, Space-zee commented
https://app.clickup.com/t/860pdf480

2022-12-30 11:16 UTC, Space-zee commented
https://app.clickup.com/t/860pbrmcv

2022-12-30 11:17 UTC, ruslanpalagin approved these changes

2022-12-30 11:17 UTC, ruslanpalagin commented on frontend/deploys/localhost.json
> +  "Usdt": "0xB1fCe46677aEF6F08c759357a4E16d020E76c562",
please clean redundant addresses as it was before

2022-12-30 11:18 UTC, ruslanpalagin commented on frontend/app/shared/walletsConnect/chainInfo.ts
> +    'localhost': 'localhost',
please use FF_RPC_NAME instead of changing the code

2022-12-30 11:18 UTC, merged