FE - Set up Storybook
binaryx-protocol/binaryx_app pull request #197
Opened 2023-01-26 16:19 UTC by Space-zee

https://app.clickup.com/t/35jvwp7

2023-01-27 09:47 UTC, ruslanpalagin requested changes

2023-01-27 09:47 UTC, ruslanpalagin commented on frontend/stories/button.css
> +.storybook-button {
maybe it's better to remove demo files?
We could add some of our component as an example

2023-01-27 09:48 UTC, ruslanpalagin commented
Looks good.
I want to run SB before merge.

2023-01-27 11:34 UTC, Space-zee commented on frontend/stories/button.css
> +.storybook-button {
+

2023-01-27 11:34 UTC, Space-zee commented on frontend/stories/button.css
> +.storybook-button {
added switcher component

2023-01-30 07:46 UTC, ruslanpalagin approved these changes
cool!

2023-01-30 07:46 UTC, merged