ADP updates
binaryx-protocol/binaryx_app pull request #220
Opened 2023-02-02 17:30 UTC by Space-zee

https://app.clickup.com/t/860przkxc

2023-02-02 17:31 UTC, Space-zee commented
https://app.clickup.com/t/860pt48v8

2023-02-02 20:08 UTC, ruslanpalagin requested changes

2023-02-02 20:08 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetInfo/Tabs/TabWithProgress/index.tsx
> +  }, [offset])
Note: react is slow comparing to native js handling.
You may want to use native js in a future in such cases.

2023-02-02 20:08 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetInfo/Tabs/index.tsx
> +  const detailsSection = document.getElementById('details');
what about useRef here?
It should be much more stable

2023-02-02 20:08 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetInfo/styles.module.scss
> +  z-index: 9;
z-index must be defined globally to avoid complexity.
not all of them... only what MAY interact/overlap with other components.
use css var

2023-02-02 20:08 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetInvest/index.tsx
> +        router.push({hash: 'root'})
view must not be responsible for application navigation
is it possible to move into model/controller?

2023-02-02 20:08 UTC, ruslanpalagin commented on frontend/app/features/kyc/controllers/KycController.tsx
> +        if (!allowanceForAsset || Number(ethers.utils.formatUnits(allowanceForAsset, 6)) < Number(form.values.amount)) {
such calculations - looks like should be in a model.
basically ALL business logic should be in a model

2023-02-03 11:53 UTC, Space-zee commented on frontend/app/features/assets/views/AssetInfo/Tabs/index.tsx
> +  const detailsSection = document.getElementById('details');
+

2023-02-03 11:59 UTC, Space-zee commented on frontend/app/features/assets/views/AssetInfo/styles.module.scss
> +  z-index: 9;
+

2023-02-03 12:02 UTC, Space-zee commented on frontend/app/features/assets/views/AssetInvest/index.tsx
> +        router.push({hash: 'root'})
+

2023-02-03 14:28 UTC, ruslanpalagin approved these changes

2023-02-03 14:28 UTC, merged