Remove SeriesMaster
binaryx-protocol/binaryx_app pull request #222
Opened 2023-02-02 18:31 UTC by boivlad

Task - https://app.clickup.com/t/860pr3qk4

2023-02-02 20:12 UTC, ruslanpalagin requested changes

2023-02-02 20:12 UTC, ruslanpalagin commented on contracts_arbitrum/deploy/dev/deploy/deployAccessManager.ts
> +  const tx2 = await accessManager.addSuperOracle(coreManager.address)
I can hardly agree with this... It looks like a workaround. 
Is there another way?

2023-02-03 10:00 UTC, boivlad commented on contracts_arbitrum/deploy/dev/deploy/deployAccessManager.ts
> +  const tx2 = await accessManager.addSuperOracle(coreManager.address)
This is for the listing by coreManager. We can add the core manager separately, but it will be more difficult.

2023-02-03 10:42 UTC, ruslanpalagin approved these changes

2023-02-03 10:50 UTC, merged