Asset page fixes
binaryx-protocol/binaryx_app pull request #255
Opened 2023-02-17 18:17 UTC by Space-zee

https://app.clickup.com/t/860pyhtge

2023-02-18 17:02 UTC, ruslanpalagin requested changes

2023-02-18 17:02 UTC, ruslanpalagin commented on frontend/app/features/assets/controllers/AssetsDetailsController.tsx
> +        $doLoadBalanceForAsset()
I am tired to say that this is a anti-jotai pattern :) 
Please analyze if you can easily put in a model these two:
$doLoadAssetBoughtHistory();
        $doLoadBalanceForAsset()

2023-02-18 17:08 UTC, ruslanpalagin requested changes

2023-02-18 17:08 UTC, ruslanpalagin commented on frontend/app/features/assets/controllers/AssetsDetailsController.tsx
> +                       isLoading={!$asset || !balanceOfAsset || !$assetSellProgress || $asset.assetAddress !== assetAddress || !$apiBoughtHistory}/>
Prefer to avoid making such decision out of model. 
Please consider creating getter in model that can say clearly if this is still loading.

2023-02-20 07:46 UTC, boivlad requested changes

2023-02-20 07:46 UTC, boivlad commented on frontend/app/features/assets/views/AssetInvestCalculate/index.tsx
> +                      defaultValue={Number(balanceOfAsset)}/>
Possible value of balanceOfAsset is null

2023-02-23 12:19 UTC, Space-zee commented on frontend/app/features/assets/views/AssetInvestCalculate/index.tsx
> +                      defaultValue={Number(balanceOfAsset)}/>
there will be zero

2023-02-23 12:19 UTC, Space-zee commented on frontend/app/features/assets/controllers/AssetsDetailsController.tsx
> +                       isLoading={!$asset || !balanceOfAsset || !$assetSellProgress || $asset.assetAddress !== assetAddress || !$apiBoughtHistory}/>
+

2023-02-23 12:38 UTC, ruslanpalagin requested changes
Much cleaner

2023-02-23 12:38 UTC, ruslanpalagin commented on frontend/app/shared/assetModel/assetDetailsModel.ts
> +import {OrderHistory} from "../../features/account/models/accountModel";
Here Shared module imports "account" feature which is not welcome)

2023-02-23 12:54 UTC, ruslanpalagin approved these changes

2023-02-23 14:02 UTC, boivlad approved these changes

2023-02-23 14:17 UTC, merged