feat: suer testnet prtopgress
binaryx-protocol/binaryx_app pull request #311
Opened 2023-03-07 10:02 UTC by Space-zee

2023-03-07 19:41 UTC, Space-zee commented
https://app.clickup.com/t/860q3gfx3

2023-03-08 09:48 UTC, ruslanpalagin requested changes

2023-03-08 09:48 UTC, ruslanpalagin commented on api/src/features/users/users.module.ts
> +    TypeOrmModule.forFeature([User]),
please remove user entity. it's not in use.
P.S user module was an example module

2023-03-08 09:48 UTC, ruslanpalagin commented on frontend/app/shared/header/models/userTestnetProgress.ts
> +    const response: any = await httpClient.fetch(`/users/userTestnetProgress/${userAddress}`, {
please use apiPaths in a future

2023-03-08 11:51 UTC, Space-zee commented on api/src/features/users/users.module.ts
> +    TypeOrmModule.forFeature([User]),
+

2023-03-08 11:52 UTC, Space-zee commented on frontend/app/shared/header/models/userTestnetProgress.ts
> +    const response: any = await httpClient.fetch(`/users/userTestnetProgress/${userAddress}`, {
+

2023-03-08 14:39 UTC, ruslanpalagin approved these changes

2023-03-08 14:39 UTC, merged