feat: contracts upgrade and audit fixes
binaryx-protocol/binaryx_app pull request #333
Opened 2023-03-14 09:48 UTC by Space-zee

2023-03-14 13:56 UTC, ruslanpalagin approved these changes

2023-03-15 08:26 UTC, ruslanpalagin requested changes
Waiting for the DEV fix

2023-03-15 12:41 UTC, boivlad approved these changes

2023-03-15 12:44 UTC, ruslanpalagin approved these changes

2023-03-15 12:44 UTC, merged