Asset List Page redesign
binaryx-protocol/binaryx_app pull request #336
Opened 2023-03-14 17:34 UTC by Space-zee

https://app.clickup.com/t/860q7cpru

2023-03-16 20:41 UTC, ruslanpalagin requested changes

2023-03-16 20:41 UTC, ruslanpalagin commented on frontend/app/features/assets/controllers/AdminAssetsListController.tsx
> +    if(assetsCombined){
is that possible to use model like I proposed (see in pm) ?

2023-03-16 20:41 UTC, ruslanpalagin commented on frontend/app/features/assets/models/assetsListModel.ts
> +  const collectedNext = (Number(ethers.utils.formatEther(next.sellProgress.maxTotalSupply)) - Number(ethers.utils.formatEther(next.sellProgress.leftToBuy))) / Number(ethers.utils.formatEther(next.sel
in the assetV2
there is a "computed" object which is reserved to keep UI & helpers variables. 
It's better to calculate such numbers there and just compare those here in the sort function.

2023-03-16 20:41 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetList/AssetListItem/index.tsx
> +  const totalPropertyPrice = tokensTotal * tokenPrice;
must be in model:
assetV2.computed.totalPropertyPrice 
or something like that.

2023-03-16 20:41 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetList/AssetListMainItem/index.tsx
> +  const collected = (tokensTotal - tokensLeft) / tokensTotal * 100;
should be in model

2023-03-16 20:42 UTC, ruslanpalagin commented
Story looks very good actually. Thank you!

2023-03-17 10:35 UTC, Space-zee commented on frontend/app/features/assets/views/AssetList/AssetListItem/index.tsx
> +  const totalPropertyPrice = tokensTotal * tokenPrice;
+

2023-03-17 10:35 UTC, Space-zee commented on frontend/app/features/assets/views/AssetList/AssetListMainItem/index.tsx
> +  const collected = (tokensTotal - tokensLeft) / tokensTotal * 100;
+

2023-03-17 10:35 UTC, Space-zee commented on frontend/app/features/assets/models/assetsListModel.ts
> +  const collectedNext = (Number(ethers.utils.formatEther(next.sellProgress.maxTotalSupply)) - Number(ethers.utils.formatEther(next.sellProgress.leftToBuy))) / Number(ethers.utils.formatEther(next.sel
+

2023-03-17 12:34 UTC, merged