Implement waitlist component
binaryx-protocol/binaryx_app pull request #430
Opened 2023-04-07 13:32 UTC by aslife

https://app.clickup.com/t/860qf2d3t

2023-04-10 13:49 UTC, aslife commented
Solved conflicts

2023-04-13 08:55 UTC, dmitriy-green commented on api/src/features/users/users.service.ts
> +    }
Why do we need this? We can make a request from the frontend. No need to add this logic on the backend

2023-04-13 08:57 UTC, dmitriy-green commented on frontend/app/features/assets/views/WaitList/WaitList.tsx
> +        <a href={'/'} className={s.socialLink}><TelegramIcon style={{position: "relative", left: '-2px'}}/></a>
`/`  path for the social links?

2023-04-13 14:55 UTC, ruslanpalagin requested changes

2023-04-13 14:55 UTC, ruslanpalagin commented on frontend/app/features/assets/views/WaitList/WaitList.tsx
> +    setValidEmail(validator.isEmail(email) ? true : false);
Need to replace with existing validator.
Remove "validator" from package

2023-04-13 14:55 UTC, ruslanpalagin commented on api/package.json
> +    "axios": "^1.3.5",
why do you need axios & nestjs/axios ?
Can we remove it please?

2023-04-13 15:03 UTC, ruslanpalagin approved these changes
I am not happy with this pr.
Created task to process comments https://app.clickup.com/t/85zrwu758

2023-04-13 15:03 UTC, merged