feat: wallet page
binaryx-protocol/binaryx_app pull request #473
Opened 2023-04-21 16:04 UTC by Space-zee

2023-04-28 17:20 UTC, Space-zee commented
Note: Need to deploy UI provider

2023-05-01 20:32 UTC, ruslanpalagin requested changes

2023-05-01 20:32 UTC, ruslanpalagin commented on frontend/app/core/walletsConnect/chainInfo.ts
> +        oraclePriceAddress: '0xab594600376ec9fd91f8e885dadf0ce036862de0'
let's use deploys to configure smart contracts addresses as a single place of truth

2023-05-02 08:55 UTC, Space-zee commented on frontend/app/core/walletsConnect/chainInfo.ts
> +        oraclePriceAddress: '0xab594600376ec9fd91f8e885dadf0ce036862de0'
+

2023-05-02 09:52 UTC, ruslanpalagin approved these changes

2023-05-02 09:52 UTC, ruslanpalagin commented on contracts/deployConfig.json
>      "ChainLinkPrice": "0x0A6513e40db6EB1b165753AD52E80663aeA50545"
UsdtPriceOracle

2023-05-02 09:52 UTC, merged