feat:asset-listing
binaryx-protocol/binaryx_app pull request #76
Opened 2022-11-29 14:37 UTC by Space-zee

2022-11-30 08:07 UTC, ruslanpalagin requested changes
Just 1 minor request and let's merge)

2022-11-30 08:07 UTC, ruslanpalagin commented on src/client/app/features/assets/views/AssetFormFields/index.tsx
> +        <BaseInput  placeholder={'Property name'} title={'Property name+'}/>
Please comment this out to keep the form working

2022-11-30 08:48 UTC, Space-zee commented on src/client/app/features/assets/views/AssetFormFields/index.tsx
> +        <BaseInput  placeholder={'Property name'} title={'Property name+'}/>
fixed

2022-11-30 09:57 UTC, ruslanpalagin approved these changes

2022-12-01 06:55 UTC, boivlad approved these changes

2022-12-01 07:56 UTC, merged