Feature/property page
binaryx-protocol/binaryx_app pull request #88
Opened 2022-12-10 21:53 UTC by Space-zee

2022-12-12 07:41 UTC, Space-zee commented
https://app.clickup.com/t/33yxp9c

2022-12-12 10:35 UTC, ruslanpalagin requested changes

2022-12-12 10:35 UTC, ruslanpalagin commented on frontend/app/features/assets/controllers/AssetsDetailsController.module.scss
> +@media screen and (max-width: 480px) {
why screen only?

2022-12-12 10:35 UTC, ruslanpalagin commented on frontend/app/features/assets/models/tokenBuyValidator.ts
> +  isAmountValid(formData: {amount: number}, tokensLeft: number, userBalance: number, tokenPrice: number) {
there is much better way here to validate, but let's keep as it is for now

2022-12-12 10:35 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetInfo/Tabs/Tabs/index.tsx
> +              <Image src={bedAIcon} alt={'bedAIcon'}/>
you can simply put src="/public/feature/assets/bed.svg" 
isn't it good enough?

2022-12-12 10:35 UTC, ruslanpalagin commented on frontend/app/features/assets/views/InvestInput/index.tsx
> +export const InvestInput = (props: Props) => {
1. that's what I ment to NOT put validation into form nor inputs
2. this is not an input - this is InvestForm component. Just validation must be in model (or at least in contoller)

2022-12-12 10:35 UTC, ruslanpalagin commented on frontend/app/features/assets/views/Location/index.tsx
> +           // @ts-ignore
please do not abuse ts-ignore

2022-12-12 10:35 UTC, ruslanpalagin commented on frontend/app/styles/globalVariables.css
> +  --max-width_mobile: 480px;
have you checked all the pages to make sure you did not break anything?

2022-12-12 10:35 UTC, ruslanpalagin commented on frontend/app/hooks/useWindowSize.ts
> +      setWindowSize(window.innerWidth);
it's bad practice to use setState on each event. 
you should add throttle/debounce in such a case...

up to you - we can optimize this later

2022-12-12 12:38 UTC, Space-zee commented on frontend/app/features/assets/views/Location/index.tsx
> +           // @ts-ignore
+

2022-12-12 12:38 UTC, Space-zee commented on frontend/app/features/assets/views/InvestInput/index.tsx
> +export const InvestInput = (props: Props) => {
+

2022-12-12 15:14 UTC, Space-zee commented on frontend/app/features/assets/controllers/AssetsDetailsController.module.scss
> +@media screen and (max-width: 480px) {
+

2022-12-12 16:07 UTC, Space-zee commented on frontend/app/features/assets/models/tokenBuyValidator.ts
> +  isAmountValid(formData: {amount: number}, tokensLeft: number, userBalance: number, tokenPrice: number) {
+

2022-12-12 17:09 UTC, Space-zee commented on frontend/app/hooks/useWindowSize.ts
> +      setWindowSize(window.innerWidth);
+

2022-12-13 12:43 UTC, ruslanpalagin requested changes

2022-12-13 12:43 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetInvest/index.tsx
> +  const router = useRouter();
Please avoid usage router in views.
Where to navigate - is a business logic and should be managed by controller or model

2022-12-13 12:43 UTC, ruslanpalagin commented on frontend/app/features/assets/views/InvestInput/index.tsx
> +      setInvestAmount(e.target.value);
Please use views naming: 
 setInvestAmount -> onAmountChange

2022-12-13 12:43 UTC, ruslanpalagin commented on frontend/package.json
> +    "@types/next": "^9.0.0",
Cool, thanks

2022-12-13 19:04 UTC, ruslanpalagin approved these changes
Great progress, thanks!

2022-12-13 19:05 UTC, merged