Feature/list property
binaryx-protocol/binaryx_app pull request #92
Opened 2022-12-15 20:43 UTC by Space-zee

2022-12-15 22:31 UTC, Space-zee commented
https://app.clickup.com/t/33yxp94

2022-12-16 09:38 UTC, ruslanpalagin requested changes

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/features/assets/controllers/NewAssetController.tsx
> +  const [currentForm, setCurrentForm] = useState<UiForm<any>>(generalInfoForm)
please replace any with values type

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/features/assets/controllers/NewAssetController.tsx
> +                            onCurrentFormChange={setCurrentForm}/> : <><p>Please Connect your wallet!</p></>
Looks good but formatting is weird. What editor do you use?

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/features/assets/models/newAssetModel.ts
> +const defaultAttrs = (): DefaultAssetListAttr => ({
maybe 4 separated initializes is better?

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/features/assets/models/newAssetModel.ts
> +    images: [''],
I would advice to use an empty array as a default value. Or even null

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/features/assets/models/newAssetModel.ts
> +    tokenAmount: 0,
Just a note: I am not sure this is a good UX to show 0 by default. Usually I do "null" in model and "" (empty string) on UI

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/features/assets/models/newAssetModel.ts
> +export const $generalInfoForm = atom<UiForm<any>>({
any - can we replace with values type?

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetListing/index.tsx
> +  const backButton = () => {
backButton -> onBackButtonClick

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/shared/ui/views/BaseInput.tsx
> +  inputType?: 'number' | 'string';
I like this idea of inputProps proxying.
With this inputType is a part of inputProps, no?

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/shared/ui/views/BaseSelect.module.scss
> +.select{
select - could it be removed from here?

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/shared/ui/views/BaseInput.tsx
> +// const DropDown = (props: DropDownProps) => {
Is this the time to remove comments?

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/shared/ui/views/BaseSelect.tsx
> +import {ArrowIconWithoutLine} from "../../../features/assets/views/ArrowIconWithoutLine";
Shared component MUST NOT import features.
Shared components MUST be reusable. 
So: 
1. please make all shared inputs feature-agnostic:
2. also (as a part of previous comments) - do not pass form and form type. You MAY pass just value/theme/onChange

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/app/shared/ui/views/TextArea.tsx
> +  const {placeholder, title, onChange, name, inputProps} = props
This is good. The rest shared components should be like this one

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/package.json
> +    "@types/react-select-country-list": "^2.2.1",
Note: Adding a library we must analyze build size to make sure we do not exceed rational limits

2022-12-16 09:38 UTC, ruslanpalagin commented on frontend/pages/_app.tsx
> +            </ThemeProvider>
Please adjust your editor to use .editorconfig (2 spaces, not 4)

2022-12-16 14:57 UTC, Space-zee commented on frontend/app/features/assets/controllers/NewAssetController.tsx
> +  const [currentForm, setCurrentForm] = useState<UiForm<any>>(generalInfoForm)
+

2022-12-16 15:00 UTC, Space-zee commented on frontend/app/features/assets/views/AssetListing/index.tsx
> +  const backButton = () => {
+

2022-12-16 15:00 UTC, Space-zee commented on frontend/app/shared/ui/views/BaseInput.tsx
> +  inputType?: 'number' | 'string';
+

2022-12-16 15:01 UTC, Space-zee commented on frontend/app/shared/ui/views/BaseSelect.module.scss
> +.select{
+

2022-12-16 15:04 UTC, Space-zee commented on frontend/app/shared/ui/views/BaseSelect.tsx
> +import {ArrowIconWithoutLine} from "../../../features/assets/views/ArrowIconWithoutLine";
+

2022-12-19 11:38 UTC, ruslanpalagin requested changes

2022-12-19 11:38 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetListing/RentalManagementForm/index.tsx
> +  inputProps: (form: UiForm<any>, name: string) => { name: string, value: any, "aria-invalid": string[] | undefined };
can we fix this any?
UiForm< any >

2022-12-19 11:38 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetListing/index.tsx
> +  currentForm: UiForm<any>;
UiForm< any >

2022-12-19 11:38 UTC, ruslanpalagin commented on frontend/app/shared/ui/views/BaseSelect.tsx
> +    onChange(inputRef.current)
why do you need this ref at all?
could we simply emit new value?

2022-12-19 11:38 UTC, ruslanpalagin commented on frontend/app/shared/ui/views/TextArea.tsx
> +                onChange={debounce(onChange, 1000)}
Note: I am afraid this is incorrect.
It's much safer to useCallback
this is a good article https://dmitripavlutin.com/react-throttle-debounce/

2022-12-19 11:49 UTC, Space-zee commented on frontend/app/features/assets/views/AssetListing/index.tsx
> +  currentForm: UiForm<any>;
+

2022-12-19 12:25 UTC, ruslanpalagin approved these changes

2022-12-19 12:25 UTC, merged