Feature/marketplace mobile
binaryx-protocol/binaryx_app pull request #98
Opened 2022-12-19 13:33 UTC by Space-zee

2022-12-19 14:47 UTC, Space-zee commented
https://app.clickup.com/t/33yxp99

2022-12-19 19:42 UTC, ruslanpalagin requested changes

2022-12-19 19:42 UTC, ruslanpalagin commented on frontend/app/features/assets/views/AssetList/AssetListItem/index.tsx
> +import {Simulate} from "react-dom/test-utils";
Please remove. I believe this is a typo, right?

2022-12-19 22:00 UTC, Space-zee commented on frontend/app/features/assets/views/AssetList/AssetListItem/index.tsx
> +import {Simulate} from "react-dom/test-utils";
yes

2022-12-20 08:03 UTC, ruslanpalagin approved these changes

2022-12-20 08:03 UTC, merged